import { Ionicons } from '@expo/vector-icons';

export type ToolCategory = 'Quick Utilities' | 'Productivity' | 'Images' | 'Documents' | 'Tools';

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: keyof typeof Ionicons.glyphMap;
  category: ToolCategory;
  route: string;
}

export const TOOLS: Tool[] = [
  {
    id: 'passport-photo',
    name: 'Passport Photo',
    description: 'Crop and arrange for printing',
    icon: 'person-circle-outline',
    category: 'Images',
    route: '/image/passport',
  },
  {
    id: 'image-compress',
    name: 'Compress Image',
    description: 'Reduce file size',
    icon: 'archive-outline',
    category: 'Images',
    route: '/image/compress',
  },
  {
    id: 'image-resize',
    name: 'Resize Image',
    description: 'Change dimensions',
    icon: 'resize-outline',
    category: 'Images',
    route: '/image/resize',
  },
  {
    id: 'exif-viewer',
    name: 'EXIF Metadata',
    description: 'View and strip photo data',
    icon: 'shield-checkmark-outline',
    category: 'Images',
    route: '/image/exif',
  },
  {
    id: 'bg-eraser',
    name: 'Background Eraser',
    description: 'Remove backgrounds instantly',
    icon: 'cut-outline',
    category: 'Images',
    route: '/image/bg-eraser',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images to a PDF document',
    icon: 'document-text-outline',
    category: 'Documents',
    route: '/document/image-to-pdf',
  },
  {
    id: 'document-scanner',
    name: 'Document Scanner',
    description: 'Scan and crop real documents',
    icon: 'scan-circle-outline',
    category: 'Documents',
    route: '/document/scanner',
  },
  {
    id: 'ocr-scanner',
    name: 'OCR Scanner',
    description: 'Extract text from images',
    icon: 'scan-outline',
    category: 'Documents',
    route: '/document/ocr',
  },
  {
    id: 'text-to-speech',
    name: 'Text-to-Speech',
    description: 'Read any text aloud',
    icon: 'volume-high-outline',
    category: 'Documents',
    route: '/document/tts',
  },
  {
    id: 'qr-generator',
    name: 'QR Generator',
    description: 'Create QR codes from text or URLs',
    icon: 'qr-code-outline',
    category: 'Tools',
    route: '/tool/qr-generator',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords',
    icon: 'key-outline',
    category: 'Tools',
    route: '/tool/password-generator',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA256 hashes from text',
    icon: 'finger-print-outline',
    category: 'Tools',
    route: '/tool/hash-generator',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, weight, data, and more',
    icon: 'swap-horizontal-outline',
    category: 'Quick Utilities',
    route: '/utility/unit-converter',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Live exchange rates',
    icon: 'cash-outline',
    category: 'Quick Utilities',
    route: '/utility/currency-converter',
  },
  {
    id: 'decision-wheel',
    name: 'Decision Wheel',
    description: 'Spin to pick randomly',
    icon: 'aperture-outline',
    category: 'Quick Utilities',
    route: '/utility/decision-wheel',
  },
  {
    id: 'encryption-tool',
    name: 'Text Encryption',
    description: 'Encrypt and decrypt text with AES',
    icon: 'lock-closed-outline',
    category: 'Tools',
    route: '/tool/encryption',
  },
  {
    id: 'random-generator',
    name: 'Random Generator',
    description: 'Numbers, dice rolls, coin flips',
    icon: 'shuffle-outline',
    category: 'Tools',
    route: '/tool/random-generator',
  },
  {
    id: 'todo-list',
    name: 'To-Do List',
    description: 'Track your daily tasks',
    icon: 'checkmark-done-outline',
    category: 'Productivity',
    route: '/productivity/todo',
  },
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Track events with alarm',
    icon: 'timer-outline',
    category: 'Productivity',
    route: '/productivity/countdown',
  },
  {
    id: 'daily-planner',
    name: 'Daily Planner',
    description: 'Schedule your day hour-by-hour',
    icon: 'calendar-outline',
    category: 'Productivity',
    route: '/productivity/planner',
  },
  {
    id: 'notes-app',
    name: 'Notes',
    description: 'Quick thoughts and ideas',
    icon: 'document-text-outline',
    category: 'Productivity',
    route: '/productivity/notes',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Find HEX, RGB, and HSL codes',
    icon: 'color-palette-outline',
    category: 'Tools',
    route: '/tool/color-picker',
  },
  {
    id: 'batch-renamer',
    name: 'Batch Renamer',
    description: 'Rename multiple files at once',
    icon: 'documents-outline',
    category: 'Tools',
    route: '/tool/batch-renamer',
  },
  {
    id: 'text-encoder',
    name: 'Base Converter',
    description: 'Omni-convert BIN, HEX, OCT, DEC',
    icon: 'code-slash-outline',
    category: 'Tools',
    route: '/tool/text-encoder',
  },
];
